sudo: required #this because we are making use of docker
services:
  - docker # this means preinstall docker service as soon as we try to run our build.
before_install
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # this file copied after you run travis encryption inside docker container.
  - curl https://sdk.cloud.google.com | bash > /dev/null; # this means install sdk and install it on our travis instance.
  - source $HOME/google-cloud-sdk/path.bash.inc # another command to configure/setup google cloud on machine.
  - gcloud components update kubectl # installing kubectl so we can later kubectl command.
  - gcloud auth activate-service-account --key-file service-account.json # tells google cloud that who we are

