apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client007
          #image: stephengrider/multi-client
          image: zafarchaudry/multi-client
          ports:
            - containerPort: 3000
